baseURL: "https://foreverfaint.github.io/"

languageCode: "zh-Hant"

title: "Dev66"

# Copyright notice. This is displayer in the footer.
copyright: "&copy; Copyright notice"

# Google Analytics API key.
googleAnalytics: "G-28KXNTEDD2"

disqusShortname: "foreverfaint-github-io"

# enable get info from git commits, such as file modification time.
# so we don't have to manually update it.
enableGitInfo: true

enableRobotsTXT: true

theme: "hugo_theme_pickles"

enableEmoji: true

# https://gohugo.io/content-management/urls/#canonicalization
canonifyURLs: false

# For a CJK summary splitting
hasCJKLanguage: true

taxonomies:
    # Enable category
    category: categories
    # Enable tag
    tag: tags
